version: '3'

services:
  db:
    image: postgres:13
    # container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=PassW0rdR4h45Ia
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  odoo:
    image: odoo:15.0
    # container_name: odoo
    restart: unless-stopped
    volumes:
      # - ./addons-enterprise:/mnt/enterprise-addons
      - ./addons-extra:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=PassW0rdR4h45Ia
volumes:
  odoo-web-data:
  odoo-db-data: